export default [
  {
    "fragment": 0,
    "text": "却说高顺引张辽击关公寨，吕布自击张飞寨，关、张各出迎战，玄德引兵两路接应。吕",
    "customMaterials": []
  },
  {
    "fragment": 1,
    "text": "布分军从背后杀来，关、张两军皆溃，玄德引数十骑奔回沛城。吕布赶来，玄德急唤城上军",
    "customMaterials": []
  }, {
    "fragment": 2,
    "text": "士放下吊桥。吕布随后也到。城上欲待放箭，又恐射了玄德。被吕布乘势杀入城门，把门将",
    "customMaterials": []
  }, {
    "fragment": 3,
    "text": "士，抵敌不住，都四散奔避。吕布招军入城。玄德见势已急，到家不及，只得弃了妻小，穿",
    "customMaterials": []
  }, {
    "fragment": 4,
    "text": "城而过，走出西门，匹马逃难，吕布赶到玄德家中，糜竺出迎，告布曰：吾闻大丈夫不废",
    "customMaterials": []
  }, {
    "fragment": 5,
    "text": "人之妻子。今与将军争天下者，曹公耳。玄德常念辕门射赖之恩，不敢背将军也。今不得已",
    "customMaterials": []
  }, {
    "fragment": 6,
    "text": "而投曹公，惟将军怜之。布曰：吾与玄德旧交，岂忍害他妻子。便令糜竺引玄德妻",
    "customMaterials": []
  }, {
    "fragment": 7,
    "text": "小，去徐州安置。布自引军投山东兖州境上，留高顺、张辽守小沛。此时孙乾已逃出城外。",
    "customMaterials": []
  }, {"fragment": 8, "text": "关、张二人亦各自收得些人马，往山中住扎。", "customMaterials": []}, {
    "fragment": 9,
    "text": "且说玄德匹马逃难，正行间，背后一人赶至，视之乃孙乾也。玄德曰：吾今两弟不知",
    "customMaterials": []
  }, {
    "fragment": 10,
    "text": "存亡，妻小失散，为之奈何？孙乾曰：不若且投曹操，以图后计。玄德依言，寻小路",
    "customMaterials": []
  }, {
    "fragment": 11,
    "text": "投许都。途次绝粮，尝往村中求食。但到处，闻刘豫州，皆争进饮食。一日，到一家投宿，",
    "customMaterials": []
  }, {
    "fragment": 12,
    "text": "其家一少年出拜，问其姓名，乃猎户刘安也。当下刘安闻豫州牧至，欲寻野味供食，一时不",
    "customMaterials": []
  }, {
    "fragment": 13,
    "text": "能得，乃杀其妻以食之。玄值曰：此何肉也？安曰：乃狼肉也。玄德不疑，乃饱食了一顿，天晚就宿。",
    "customMaterials": []
  }, {
    "fragment": 14,
    "text": "惊问，方知昨夜食者，乃其妻之肉也。玄德不胜伤感，洒泪上马。刘安告玄德曰：本欲相",
    "customMaterials": []
  }, {
    "fragment": 15,
    "text": "随使君，因老母在堂，未敢远行。玄德称谢而别，取路出梁城。忽见尘头蔽日，一彪大军",
    "customMaterials": []
  }, {
    "fragment": 16,
    "text": "来到。玄德知是曹操之军，同孙乾径至中军旗下，与曹操相见，具说失沛城、散二弟、陷妻",
    "customMaterials": []
  }, {
    "fragment": 17,
    "text": "小之事。操亦为之下泪。又说刘安杀妻为食之事，操乃令孙乾以金百两往赐之。",
    "customMaterials": []
  }]
